Adding data models and initial Team page
Cosinity/pokemon-draft-site pull request #2
Opened 2022-11-20 16:10 UTC by Cosinity

2022-11-20 17:11 UTC, samuel-peter-chowdhury requested changes
Looks good. Had just a couple comments on the Roster model. I notice that you're using IDs for most fields in the model instead of using models/resources (i.e. userID instead of User). I think this makes sense, but will mean we're making tons of calls to the backend. Might be worth taking another look down the road to see if using the models themselves causes much of a slow down.

2022-11-20 17:11 UTC, samuel-peter-chowdhury commented on frontend/src/app/shared/models/season-roster.model.ts
> +  public roster: Pokemon[];
Instead of reusing roster, lets call this field 'pokemon' or 'pokemon_list' or something.

2022-11-20 17:11 UTC, samuel-peter-chowdhury commented on frontend/src/app/shared/models/season-roster.model.ts
> +export class SeasonRoster {
I think we could just call this 'Roster' for simplicity sake. It will still be on the season level, but I don't think we need such a long name.

2022-11-21 02:38 UTC, Cosinity commented
> Looks good. Had just a couple comments on the Roster model. I notice that you're using IDs for most fields in the model instead of using models/resources (i.e. userID instead of User). I think this makes sense, but will mean we're making tons of calls to the backend. Might be worth taking another look down the road to see if using the models themselves causes much of a slow down.

I agree, I just wanted to use IDs at first to avoid circular references, and we can update them once we have a better idea of what the backend relationships look like.

2022-11-29 02:32 UTC, samuel-peter-chowdhury approved these changes
LGTM

2022-11-29 03:06 UTC, merged